name: Generate Snake Animation

on:
  # Atualiza todos os dias 맙 23:00 UTC (20h no hor치rio de Bras칤lia)
  schedule:
    - cron: "0 23 * * *"

  # Permite executar manualmente pelo GitHub Actions
  workflow_dispatch:

  # Executa quando h치 mudan칞as na branch principal
  push:
    branches:
      - main
      - master

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Clona seu reposit칩rio
      - name: Checkout do reposit칩rio
        uses: actions/checkout@v4

      # Gera a anima칞칚o da cobra
      - name: Gerar Snake 游냀
        uses: Platane/snk@v3
        with:
          github_user_name: Ronaldo94-cf
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Publica o resultado no branch "output"
      - name: Publicar no branch output 游닋
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
